### ISSUE TITLE
Module (custom scope) dependencies aren't fully transitive

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#171] opened 2021-12-14 13:54 UTC
I have the following scopes, and a couple of problems:

1. I can't create a scope unless there's at least one object in it, which means I can't easily refactor out dependencies in some cases. Note the pointless `Foo` class below.
2. The below code doesn't actually work because classes marked with e.g. `@LinuxScope` can't see the `Build` dependency ("no dependency provided" error), even though as you can see, if you trace through the scope dependencies, it is there.

My guess is that nobody has tried to make chains of scope dependencies like this before :)

```
@Scope
@InjectModule(
    requires = [
        Build::class,
        AppConfigView::class,
        KeyManager::class,
        Scopes::class
    ]
)
annotation class BuildScope

@BuildScope
class Foo(build: Build)

/**
 * A dependency injection scope for download site/repository generation.
 * Classes annotated with this can be fetched by injecting [Scopes] and then calling [Scopes.site].
 */
@Scope
@InjectModule(
    requires = [ BuildScope::class ]
)
annotation class SiteScope

/**
 * A dependency injection scope for tasks that can target any machine, but must be instantiated for one specifically.
 */
@Scope
@InjectModule(
    requires = [
        BuildScope::class,
        Machine::class,
        OS::class,
        CPUArchitecture::class
    ]
)
annotation class MachineScopedTask

/** Windows package specific tasks. */
@Scope
@InjectModule(requires = [ MachineScopedTask::class ])
annotation class WindowsScope

/** Mac package specific tasks. */
@Scope
@InjectModule(requires = [ MachineScopedTask::class ])
annotation class MacScope

/** Linux package specific tasks. */
@Scope
@InjectModule(requires = [ MachineScopedTask::class, CLibrary::class ])
annotation class LinuxScope
```

**Comment by rbygrave** [comment] 2021-12-15 21:04
> e.g. @LinuxScope can't see the Build dependency ("no dependency provided" error), even though as you can see, if you trace through the scope dependencies, it is there.

Yes I see.  Said another way, currently the search/check for a dependency of a scope isn't **_recursive_**. It very much looks like `ScopeInfo` only searches scope dependency one level deep instead of recursively searching up all dependent scope.

The code in question in `ScopeInfo` at  `boolean providedByOtherModule(String dependency)` and `boolean providesDependency(String dependency)` ... this is where the problem is in that this isn't recursive.

Ok, next step will be a failing test and then I think we can sort it there in `ScopeInfo`.

**Comment by rbygrave** [comment] 2021-12-15 23:21
We have a fix for 2.  

Now looking at .. "I can't create a scope unless there's at least one object in it"

**Comment by rbygrave** [comment] 2021-12-15 23:47
Ah, so it does look like this issue is also fixed by the recursive search.  That is, creating a new empty scope in between MachineScope and BuildScope now works fine.  I do see for the empty scope that no module is generated but that seems correct (as there is nothing to wire for that empty scope), and now with the recursive search it does go and search up through that empty scope.

So yeah, looks like the fix takes care of both of these 2 issues.

**Closed** 2021-12-16 00:24 UTC
Labels: bug

**Comment by mikehearn** [comment] 2021-12-16 09:48
I think the issue with not creating a module is, how do you create a scope that inherits from it? With the BeanScopeBuilder, you have to specify the inheritance by specifying modules.

**Comment by rbygrave** [comment] 2021-12-16 11:05
> how do you create a scope that inherits from it?

We don't need to. We can build it in both "nested form" and in "flattened form" without the empty module.

Have a look at these 2 tests which do that:

https://github.com/avaje/avaje-inject/blob/master/inject-test/src/test/java/org/example/custom4/LinuxScopeTest.java#L59
https://github.com/avaje/avaje-inject/blob/master/inject-test/src/test/java/org/example/custom4/LinuxScopeTest.java#L11

Note that here we don't need the module for the IntentionallyEmptyScope ... (the module doesn't exists for it but that's fine)
https://github.com/avaje/avaje-inject/blob/master/inject-test/src/test/java/org/example/custom4/IntentionallyEmptyScope.java#L8

**Comment by rbygrave** [comment] 2021-12-16 22:33
> how do you create a scope that inherits from it?

I think my wording was poor.  If a scope inherits from an empty scope, then the empty scope just **_isn't needed_** in order to create the scope.

So in the tests we need the 'parent' of the empty scope ... so when creating the `linuxScope` we used the `machineScope` as the parent (sort of skipping the empty `IntentionallyEmptyScope` altogether). As per:
https://github.com/avaje/avaje-inject/blob/master/inject-test/src/test/java/org/example/custom4/LinuxScopeTest.java#L40  

Hopefully that is a better explanation.

**Comment by mikehearn** [comment] 2021-12-21 18:43
Thanks, I tried it out and can confirm it works.
